import test from 'node:test';import assert from 'node:assert/strict';import {defaults,dimensions,layout,cellPosition,migrateSettings} from '../src/layout.js';
test('paper dimensions and orientation',()=>{assert.deepEqual(dimensions(defaults),[210,297]);assert.deepEqual(dimensions({...defaults,paper:'a5',orientation:'landscape'}),[210,148]);});
test('long content paginates without loss',()=>{const s={...defaults,text:'字'.repeat(6000)};const l=layout(s);assert.equal(l.units.filter(Boolean).length,6000);assert.ok(l.pages>1);assert.ok(l.top+(l.rows-1)*l.rowPitch+l.cellHeight<=l.h-s.margin-(s.showPage?8:0));});
test('vertical starts top right and advances down',()=>{const s={...defaults,direction:'vertical'};const l=layout(s);assert.ok(cellPosition(0,l,s).x>cellPosition(l.rows,l,s).x);assert.ok(cellPosition(1,l,s).y>cellPosition(0,l,s).y);});
test('unicode supplementary characters preserved',()=>{assert.equal(layout({...defaults,text:'𠮷😀'}).units.filter(Boolean).length,2);});
test('empty text produces usable blank page',()=>{assert.equal(layout({...defaults,text:''}).pages,1);});
test('ruled text retains lines and repeats',()=>{const l=layout({...defaults,grid:'ruled',text:'one\ntwo',lineRepeat:2,blankRows:1});assert.deepEqual(l.units,['one','one','','two','two','']);});
test('copy mode gives every character its own practice row',()=>{const s={...defaults,mode:'copy',text:'生活'};const l=layout(s);assert.equal(l.units[0],'生');assert.equal(l.units[l.cols],'活');assert.equal(l.units.filter(Boolean).length,2);});
test('character and input-line repetitions are independent',()=>{const s={...defaults,text:'天地',charRepeat:2,lineRepeat:3};const l=layout(s);for(let n=0;n<3;n++)assert.equal(l.units.slice(n*l.cols,n*l.cols+4).join(''),'天天地地');assert.equal(l.units.filter(Boolean).length,12);});
test('line repetition preserves wrapped blocks and adds blanks after repetitions',()=>{const s={...defaults,text:'ABCDEFGHIJK',charRepeat:1,lineRepeat:2,blankRows:1};const l=layout(s);const block=Math.ceil(11/l.cols)*l.cols;assert.deepEqual(l.units.slice(0,block),l.units.slice(block,2*block));assert.equal(l.units.length,2*block+l.cols);});
test('ruled character repetition preserves word spaces, line repeat then blank',()=>{assert.deepEqual(layout({...defaults,grid:'lined',text:'AB CD',charRepeat:2,lineRepeat:2,blankRows:1}).units,['AABB CCDD','AABB CCDD','']);});
test('copy mode places requested model count and repeats whole practice group',()=>{const s={...defaults,mode:'copy',text:'天地',charRepeat:2,lineRepeat:2};const l=layout(s);assert.equal(l.units.filter(Boolean).join(''),'天天地地天天地地');assert.equal(l.units[0],'天');assert.equal(l.units[1],'天');assert.equal(l.units[2],'');});
test('vertical input-line repeats become columns in right-to-left order',()=>{const s={...defaults,text:'天地',charRepeat:2,lineRepeat:2,direction:'vertical'};const l=layout(s);assert.equal(l.units.slice(0,4).join(''),'天天地地');assert.equal(l.units.slice(l.rows,l.rows+4).join(''),'天天地地');});
test('grapheme clusters remain intact when repeated',()=>{const l=layout({...defaults,text:'e\u0301👩‍💻',charRepeat:2});assert.deepEqual(l.units.filter(Boolean),['e\u0301','e\u0301','👩‍💻','👩‍💻']);});
test('empty input lines retain a blank grid row',()=>{const l=layout({...defaults,text:'天\n\n地'});assert.equal(l.units[2*l.cols],'地');});

test('legacy repeat migrates to the relevant independent setting',()=>{assert.deepEqual(migrateSettings({grid:'ruled',repeat:3}),{grid:'ruled',lineRepeat:3});assert.deepEqual(migrateSettings({grid:'mi',repeat:2}),{grid:'mi',charRepeat:2});});
test('lined copy mode repeats model plus blank practice line as a group',()=>{assert.deepEqual(layout({...defaults,mode:'copy',grid:'lined',text:'AB',charRepeat:2,lineRepeat:2}).units,['AABB','','AABB','']);});
test('fill page repeats the complete practice pattern without changing requested repetitions',()=>{const s={...defaults,text:'天地',charRepeat:2,lineRepeat:2,fillPage:true};const plain=layout({...s,fillPage:false}),filled=layout(s);assert.deepEqual(filled.units.slice(0,plain.units.length),plain.units);assert.equal(filled.units.length,filled.capacity);assert.deepEqual(filled.units.slice(plain.units.length,plain.units.length+plain.cols),plain.units.slice(0,plain.cols));});
test('fill page completes the final ruled page and preserves earlier pages',()=>{const s={...defaults,grid:'lined',text:'one\ntwo',fillPage:true};const l=layout(s);assert.equal(l.units.length,l.capacity);assert.deepEqual(l.units.slice(0,4),['one','two','one','two']);const long=layout({...s,text:Array.from({length:l.capacity+1},(_,i)=>String(i)).join('\n')});assert.equal(long.pages,2);assert.equal(long.units.length,long.capacity*2);assert.equal(long.units[long.capacity],String(long.capacity));});
test('font size remains independent from grid size and line height',()=>{const base={...defaults,grid:'ruled',text:'Practice',fontSize:12};const short=layout({...base,lineHeight:14}),tall=layout({...base,lineHeight:25});assert.equal(short.cellHeight,14);assert.equal(tall.cellHeight,25);assert.ok(short.rows>tall.rows);assert.equal(base.fontSize,12);const square=layout({...defaults,text:'天地',letterSpacing:3});assert.equal(cellPosition(1,square,{...defaults,letterSpacing:3}).x-cellPosition(0,square,{...defaults,letterSpacing:3}).x,square.cellSize+3);});
test('legacy relative font scale migrates to an absolute size',()=>{assert.deepEqual(migrateSettings({size:20,fontScale:75}),{fontSize:15});assert.deepEqual(migrateSettings({size:18,fontScale:72}),{fontSize:13});});

test('square cell size follows font size at a fixed proportion',()=>{const small=layout({...defaults,fontSize:10}),large=layout({...defaults,fontSize:20});assert.equal(large.cellSize,small.cellSize*2);assert.ok(large.cols<small.cols);assert.ok(large.rows<small.rows);});
