export const languages={zh:{name:'中文',font:'Noto Serif TC',grid:'mi',note:'預設思源宋體與米字格，也可改用田字格或方格。',grids:['mi','tian','square','nine','dots','none']},en:{name:'English',font:'Cormorant Garamond',grid:'ruled',note:'預設英文四線；練習斜體手寫時可選斜線輔助格。',grids:['ruled','slant','dots','none']},ja:{name:'日本語',font:'Noto Serif JP',grid:'square',note:'預設思源明朝與方格，適合假名與漢字。',grids:['square','tian','mi','dots','none']},ko:{name:'한국어',font:'Noto Serif KR',grid:'square',note:'預設思源宋體韓文與方格，適合韓文字塊。',grids:['square','tian','dots','none']}};
export function languageDefaults(language){const l=languages[language];if(!l)throw Error('不支援的語言');return{language,font:l.font,grid:l.grid,direction:'horizontal'};}
export const categories={zh:[['poetry','古代詩詞'],['songs','經典歌曲 · 公版'],['modern','現代歌曲 · 自行匯入'],['practice','日常短句']],en:[['classics','經典名著'],['poetry','經典詩歌'],['shakespeare','莎士比亞'],['songs','經典歌曲 · 公版'],['modern','現代歌曲 · 自行匯入'],['practice','字母與日常短句']],ja:[['literature','文學名著 · 宮澤賢治'],['practice','五十音與日常短句'],['modern','歌曲 · 自行匯入']],ko:[['practice','字母與日常短句'],['modern','歌曲 · 自行匯入']]};
const entry=(id,language,category,title,author,text,source='',rights='公版原文',excerpt=false)=>({id,language,category,title,author,text,source,rights,excerpt});
export const library=[
entry("kenji-rain","ja","literature","雨ニモマケズ","宮澤賢治","雨ニモマケズ\n風ニモマケズ\n雪ニモ夏ノ暑サニモマケヌ\n丈夫ナカラダヲモチ\n慾ハナク\n決シテ瞋ラズ\nイツモシヅカニワラッテヰル","https://www.aozora.gr.jp/cards/000081/files/45630_23908.html","公版原文 · 青空文庫",true),
entry("kenji-railway","ja","literature","銀河鉄道の夜","宮沢賢治","「ではみなさんは、そういうふうに川だと云われたり、乳の流れたあとだと云われたりしていたこのぼんやりと白いものがほんとうは何かご承知ですか。」\n先生は、黒板に吊した大きな黒い星座の図の、上から下へ白くけぶった銀河帯のようなところを指しながら、みんなに問をかけました。","https://www.aozora.gr.jp/cards/000081/files/456_15050.html","公版原文 · 省略振假名，調整換行",true),
entry("alice","en","classics","Alice’s Adventures in Wonderland","Lewis Carroll · 1865","Alice was beginning to get very tired\nof sitting by her sister on the bank,\nand of having nothing to do:\nonce or twice she had peeped into the book\nher sister was reading,\nbut it had no pictures or conversations in it,\n“and what is the use of a book,” thought Alice\n“without pictures or conversations?”","https://www.gutenberg.org/files/11/11-h/11-h.htm","公版原文 · 為練習調整換行",true),
entry("pride","en","classics","Pride and Prejudice","Jane Austen · 1813","It is a truth universally acknowledged,\nthat a single man in possession of a good fortune\nmust be in want of a wife.","https://www.gutenberg.org/files/1342/1342-h/1342-h.htm","公版原文 · 為練習調整換行",true),
entry("two-cities","en","classics","A Tale of Two Cities","Charles Dickens · 1859","It was the best of times,\nit was the worst of times,\nit was the age of wisdom,\nit was the age of foolishness,\nit was the epoch of belief,\nit was the epoch of incredulity,","https://www.gutenberg.org/files/98/98-h/98-h.htm","公版原文 · 為練習調整換行",true),
entry("moby","en","classics","Moby-Dick","Herman Melville · 1851","Call me Ishmael.\nSome years ago—never mind how long precisely—\nhaving little or no money in my purse,\nand nothing particular to interest me on shore,\nI thought I would sail about a little\nand see the watery part of the world.","https://www.gutenberg.org/files/2701/2701-h/2701-h.htm","公版原文 · 為練習調整換行",true),
entry('spring','zh','poetry','春曉','孟浩然','春眠不覺曉，\n處處聞啼鳥。\n夜來風雨聲，\n花落知多少。','https://zh.wikisource.org/wiki/春曉_(孟浩然)'),
entry('night','zh','poetry','靜夜思','李白','床前明月光，\n疑是地上霜。\n舉頭望明月，\n低頭思故鄉。','https://zh.wikisource.org/wiki/靜夜思'),
entry('stork','zh','poetry','登鸛雀樓','王之渙','白日依山盡，\n黃河入海流。\n欲窮千里目，\n更上一層樓。','https://zh.wikisource.org/wiki/登鸛雀樓'),
entry('deer','zh','poetry','鹿柴','王維','空山不見人，\n但聞人語響。\n返景入深林，\n復照青苔上。','https://zh.wikisource.org/wiki/鹿柴'),
entry('farewell','zh','songs','送別','李叔同 · 1915','長亭外，古道邊\n芳草碧連天\n晚風拂柳笛聲殘\n夕陽山外山\n天之涯，地之角\n知交半零落\n一瓢濁酒盡餘歡\n今宵別夢寒','https://zh.wikisource.org/wiki/送別_(李叔同)','公版原詞',true),
entry('zh-daily','zh','practice','慢慢生活','さらさら原創','慢慢寫字，好好生活。\n把日子寫成喜歡的樣子。','','原創練習文字'),
entry('zh-seasons','zh','practice','四季筆記','さらさら原創','春日有花，夏夜有風。\n秋收一片葉，冬留一盞燈。','','原創練習文字'),
entry('tyger','en','poetry','The Tyger','William Blake · 1794','Tyger Tyger, burning bright,\nIn the forests of the night;\nWhat immortal hand or eye,\nCould frame thy fearful symmetry?','https://www.poetryfoundation.org/poems/43687/the-tyger','公版原文',true),
entry('sonnet18','en','shakespeare','Sonnet 18','William Shakespeare · 1609',"Shall I compare thee to a summer’s day?\nThou art more lovely and more temperate:\nRough winds do shake the darling buds of May,\nAnd summer’s lease hath all too short a date;",'https://www.poetryfoundation.org/poems/45087/sonnet-18-shall-i-compare-thee-to-a-summers-day','公版原文',true),
entry('sonnet116','en','shakespeare','Sonnet 116','William Shakespeare · 1609',"Let me not to the marriage of true minds\nAdmit impediments. Love is not love\nWhich alters when it alteration finds,\nOr bends with the remover to remove.",'https://en.wikisource.org/wiki/Shakespeare%27s_Sonnets/Sonnet_116','公版原文',true),
entry('star','en','songs','Twinkle, Twinkle, Little Star','Jane Taylor · 1806','Twinkle, twinkle, little star,\nHow I wonder what you are!\nUp above the world so high,\nLike a diamond in the sky.','https://en.wikisource.org/wiki/Rhymes_for_the_Nursery/The_Star','公版原詞',true),
entry('alphabet','en','practice','Uppercase & lowercase','字母練習','ABCDEFGHIJKLMNOPQRSTUVWXYZ\nabcdefghijklmnopqrstuvwxyz','','基礎字母'),
entry('en-daily','en','practice','A little time to write','さらさら原創','Make a little room for quiet.\nLet each letter take its time.\nA new page, a fresh beginning.','','原創練習文字'),
entry('hiragana','ja','practice','ひらがな · 平假名','五十音','あいうえお\nかきくけこ\nさしすせそ\nたちつてと\nなにぬねの\nはひふへほ\nまみむめも\nやゆよ\nらりるれろ\nわをん','','基礎字母'),
entry('katakana','ja','practice','カタカナ · 片假名','五十音','アイウエオ\nカキクケコ\nサシスセソ\nタチツテト\nナニヌネノ\nハヒフヘホ\nマミムメモ\nヤユヨ\nラリルレロ\nワヲン','','基礎字母'),
entry('ja-daily','ja','practice','日々のことば','さらさら原創','今日も、ゆっくり書こう。\n小さな一歩を大切に。','','原創練習文字'),
entry('hangul','ko','practice','한글 · 韓文字母','基礎音節','가나다라마바사\n아자차카타파하\n아야어여오요우유으이','','基礎字母'),
entry('ko-daily','ko','practice','오늘의 문장','さらさら原創','오늘도 천천히 써요.\n작은 기쁨을 기억해요.','','原創練習文字')
];
export function normalizeText(text){return text.replace(/^\uFEFF/,'').replace(/\r\n?/g,'\n');}
export function decodeText(buffer,encoding='auto'){const bytes=new Uint8Array(buffer);if(bytes.length>1024*1024)throw Error('請選擇 1 MB 以內的文字檔。');let codec=encoding;if(codec==='auto')codec=bytes[0]===255&&bytes[1]===254?'utf-16le':bytes[0]===254&&bytes[1]===255?'utf-16be':'utf-8';let text;try{text=normalizeText(new TextDecoder(codec,{fatal:true}).decode(bytes));}catch{throw Error('文字編碼無法辨識，請改選 Big5 或 UTF-16 後重新讀取。');}if(/[\x00-\x08\x0B\x0C\x0E-\x1F]/.test(text))throw Error('檔案包含非文字資料，請選擇純文字 TXT。');if(!text.trim())throw Error('這份文字檔是空白的。');return text;}
export function combineText(current,incoming,append=false){const result=append&&current?current+'\n'+incoming:incoming;if(result.length>6000)throw Error('合併後超過 6,000 字元，請先縮短內容；原有文字未更動。');return result;}
