import {bindContentControls} from './content-controls.js';
import {interfaceHTML} from './interface.js';
import './style.css';
import '@fontsource/noto-serif-tc/400.css';
import '@fontsource/noto-serif-jp/400.css';
import '@fontsource/noto-serif-kr/400.css';
import '@fontsource/unifrakturmaguntia/400.css';
import '@fontsource/cormorant-garamond/400.css';
import {jsPDF} from 'jspdf';
import {defaults,layout,cellPosition,isRuled,isLine,migrateSettings,graphemes} from './layout.js';
const icons={download:'<path d="M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5"/>',reset:'<path d="M3 10a9 9 0 1 1 2 8M3 4v6h6"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5"/>',check:'<path d="m5 12 4 4L19 6"/>',grid:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 12h18M12 3v18"/>',type:'<path d="M4 5h16M12 5v15M8 20h8"/>',sliders:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${icons[n]||icons.grid}</svg>`;
let s={...defaults};try{const saved=JSON.parse(localStorage.getItem('inkstone-settings'));if(saved&&saved.version===1)s={...defaults,...migrateSettings(saved.settings),font:['Noto Serif TC','Noto Serif JP','Noto Serif KR','Cormorant Garamond','UnifrakturMaguntia','serif','sans-serif','cursive'].includes(saved.settings.font)?saved.settings.font:defaults.font};}catch{}
let page=0,zoom=85,renderId=0,busy=false,autoFit=true;const fontList=[['Noto Serif TC','思源宋體 · 繁體中文'],['Noto Serif JP','思源明朝 · 日本語'],['Noto Serif KR','思源宋體 · 한국어'],['Cormorant Garamond','Cormorant · 古典英文'],['UnifrakturMaguntia','Unifraktur · 哥特體'],['serif','系統襯線體'],['sans-serif','系統無襯線體'],['cursive','系統手寫體']];
const esc=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const select=(key,label,options)=>`<label class="field">${label}<select data-key="${key}">${options.map(([v,t])=>`<option value="${v}" ${String(s[key])===String(v)?'selected':''}>${t}</option>`).join('')}</select></label>`;
const range=(key,label,min,max,step=1,unit='')=>`<label class="field range-label">${label}<output id="out-${key}">${s[key]}${unit}</output><input type="range" data-key="${key}" min="${min}" max="${max}" step="${step}" value="${s[key]}"></label>`;
const check=(key,label)=>`<label class="check"><input type="checkbox" data-key="${key}" ${s[key]?'checked':''}>${label}</label>`;
const colors=[['gridColor','格線'],['inkColor','文字'],['paperColor','紙張']];
document.querySelector('#app').innerHTML=interfaceHTML({s,esc,select,range,check,colors,fontList,icon});
function toast(msg){const e=document.querySelector('#toast');e.textContent=msg;e.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.hidden=true,4500);}
function persist(){try{localStorage.setItem('inkstone-settings',JSON.stringify({version:1,settings:s}));}catch{}}
function drawSpacedText(c,value,x,y,maxWidth,spacing){if(!spacing){c.fillText(value,x,y,maxWidth);return;}const glyphs=graphemes(value),widths=glyphs.map(g=>c.measureText(g).width),total=widths.reduce((a,b)=>a+b,0)+Math.max(0,glyphs.length-1)*spacing,compression=total>maxWidth?maxWidth/total:1;c.save();c.translate(x,y);c.scale(compression,1);let offset=0;glyphs.forEach((g,i)=>{c.fillText(g,offset,0);offset+=widths[i]+spacing;});c.restore();}
function draw(canvas,l,index,scale){canvas.width=Math.round(l.w*scale);canvas.height=Math.round(l.h*scale);const c=canvas.getContext('2d');c.scale(scale,scale);c.fillStyle=s.paperColor;c.fillRect(0,0,l.w,l.h);c.textBaseline='middle';c.fillStyle=s.inkColor;c.font='3.5px "Noto Serif TC", sans-serif';if(s.showTitle)c.fillText(s.title,s.margin,s.margin+4,l.w-2*s.margin-(s.showDate?48:0));if(s.showDate){c.textAlign='right';c.fillText('日期：____ / ____ / ____',l.w-s.margin,s.margin+4);c.textAlign='left';}if(s.showPage){c.textAlign='center';c.font='2.8px sans-serif';c.fillText(`${index+1} / ${l.pages}`,l.w/2,l.h-s.margin);c.textAlign='left';}const line=(x,y,x2,y2,dash=false)=>{c.beginPath();c.setLineDash(dash?[0.7,0.9]:[]);c.moveTo(x,y);c.lineTo(x2,y2);c.stroke();};c.strokeStyle=s.gridColor;c.lineWidth=s.lineWidth;
for(let i=0;i<l.capacity;i++){const ruled=isLine(s);let {x,y}=ruled?{x:s.margin,y:l.top+i*l.rowPitch}:cellPosition(i,l,s);let size=ruled?l.cellHeight:l.cellSize,w=ruled?l.w-2*s.margin:size;if(isRuled(s)){if(s.grid==='slant'){c.save();c.beginPath();c.rect(x,y,w,size);c.clip();c.globalAlpha=.55;const dx=size/Math.tan(s.slantAngle*Math.PI/180);for(let offset=-dx;offset<w+dx;offset+=size*.6)line(x+offset,y+size,x+offset+dx,y,true);c.restore();}if(s.grid==='lined')line(x,y+size*2/3,x+w,y+size*2/3);else for(let n=0;n<4;n++)line(x,y+size*n/3,x+w,y+size*n/3,n===1||n===2);}else if(['mi','tian','square','nine'].includes(s.grid)){c.setLineDash([]);c.strokeRect(x,y,size,size);if(['mi','tian'].includes(s.grid)){line(x+size/2,y,x+size/2,y+size,true);line(x,y+size/2,x+size,y+size/2,true);}if(s.grid==='mi'){line(x,y,x+size,y+size,true);line(x+size,y,x,y+size,true);}if(s.grid==='nine'){for(let n=1;n<3;n++){line(x+size*n/3,y,x+size*n/3,y+size,true);line(x,y+size*n/3,x+size,y+size*n/3,true);}}}else if(s.grid==='dots'){c.fillStyle=s.gridColor;for(let a=0;a<=Math.floor(w/(size/2));a++)for(let b=0;b<=2;b++){c.beginPath();c.arc(x+size*a/2,y+size*b/2,s.lineWidth*1.3,0,Math.PI*2);c.fill();}}
const text=l.units[index*l.capacity+i]||'';const first=ruled||i%(l.vertical?l.rows:l.cols)===0;if(text&&s.mode!=='blank'){c.save();c.beginPath();c.rect(x+0.4,y+0.4,w-0.8,size-0.8);c.clip();c.fillStyle=s.inkColor;c.globalAlpha=s.mode==='trace'?s.opacity/100:1;c.font=`${s.fontSize}px "${s.font}", serif`;c.textAlign=ruled?'left':'center';c.textBaseline=ruled?'alphabetic':'middle';if(ruled)drawSpacedText(c,text,x+1,y+size*2/3,w-2,s.letterSpacing);else c.fillText(text,x+size/2,y+size*0.5,w-2);c.restore();}}
}
async function render(){const id=++renderId;document.querySelector('#rendering').hidden=false;await document.fonts.load(`20px "${s.font}"`,s.text||'永Aa');await document.fonts.load('14px "Noto Serif TC"',s.title+'日期');if(id!==renderId)return;const l=layout(s);page=Math.min(page,l.pages-1);draw(document.querySelector('#preview'),l,page,3.5);document.querySelector('#rendering').hidden=true;document.querySelector('#charCount').textContent=`${Array.from(s.text).length} 字元`;document.querySelector('#paperInfo').textContent=`${s.paper.toUpperCase()} · ${l.w} × ${l.h} mm`;document.querySelector('#layoutInfo').textContent=isLine(s)?`${l.rows} 行 / 頁`:`${l.cols} 欄 × ${l.rows} 行`;document.querySelector('#pageInfo').textContent=`${page+1} / ${l.pages}`;document.querySelector('#prev').disabled=page===0;document.querySelector('#next').disabled=page===l.pages-1;document.querySelector('#fontSample').style.fontFamily=`"${s.font}",serif`;updateContext(l);if(autoFit)fit();else applyZoom();persist();}
function applyZoom(){const l=layout(s);document.querySelector('#paperWrap').style.width=`${l.w*3.78*zoom/100}px`;document.querySelector('#zoomValue').textContent=zoom+'%';}
function fit(){autoFit=true;const l=layout(s),stage=document.querySelector('#stage');zoom=Math.max(15,Math.floor(Math.min((stage.clientWidth-64)/(l.w*3.78),(stage.clientHeight-64)/(l.h*3.78))*100));applyZoom();}
function updateContext(l){contentControls?.refresh();const font=document.querySelector('[data-key="font"]');document.querySelector('#fontSample').textContent=s.text.replace(/\n/g,' ').slice(0,18)||'永遠保持練習的心。 Aa';document.querySelector('#exportSummary').textContent=`${s.paper.toUpperCase()} · ${s.orientation==='portrait'?'直向':'橫向'} · 共 ${l.pages} 頁`;document.querySelector('[data-key="direction"]').disabled=isLine(s);document.querySelector('#directionHint').hidden=!isRuled(s);document.querySelector('[data-key="lineHeight"]').disabled=!isLine(s);const typeFitHint=document.querySelector('#typeFitHint'),availableHeight=isLine(s)?s.lineHeight:l.cellSize;typeFitHint.hidden=s.fontSize<=availableHeight;typeFitHint.textContent=isLine(s)?'字體大於行高，文字可能被裁切。可提高行高或縮小字體。':'字體大於格子尺寸，文字可能被裁切。可放大格子或縮小字體。';document.querySelector('[data-key="opacity"]').disabled=s.mode!=='trace';document.querySelector('#opacityHint').textContent=s.mode==='trace'?'較淡的字樣適合描寫；較深的字樣適合初學。':'目前不是描紅模式，濃度設定暫不套用。';document.querySelector('#previewStatus').textContent='預覽已更新';const paper=document.querySelector('#paperWrap');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)paper.animate([{opacity:.7},{opacity:1}],{duration:260,easing:'ease-out'});}

function sync(){document.querySelectorAll('[data-mode]').forEach(e=>{e.classList.toggle('selected',e.dataset.mode===s.mode);e.setAttribute('aria-pressed',e.dataset.mode===s.mode);});document.querySelectorAll('[data-key]').forEach(e=>{if(e.type==='checkbox')e.checked=s[e.dataset.key];else e.value=s[e.dataset.key];});document.querySelectorAll('[data-grid]').forEach(e=>(e.classList.toggle('selected',e.dataset.grid===s.grid),e.setAttribute('aria-pressed',e.dataset.grid===s.grid)));document.querySelectorAll('output').forEach(e=>{const k=e.id.slice(4);e.textContent=s[k]+(k==='slantAngle'?'°':['fontSize','letterSpacing','lineHeight','gap','margin','lineWidth'].includes(k)?' mm':'%');});colors.forEach(([k])=>document.querySelector('#color-'+k).textContent=s[k]);render();}
let debounce;document.querySelectorAll('[data-key]').forEach(e=>e.addEventListener('input',()=>{const k=e.dataset.key;s[k]=e.type==='checkbox'?e.checked:typeof defaults[k]==='number'?Number(e.value):e.value;page=0;const out=document.querySelector('#out-'+k);if(out)out.textContent=s[k]+(k==='slantAngle'?'°':['fontSize','letterSpacing','lineHeight','gap','margin','lineWidth'].includes(k)?' mm':'%');if(k.endsWith('Color'))document.querySelector('#color-'+k).textContent=s[k];clearTimeout(debounce);debounce=setTimeout(()=>render().catch(()=>toast('字型載入失敗，請選擇其他字型。')),100);}));
const steps=['content','typography','format','style'],stepNames=['語言與內容','選擇字型','設定紙張','配色與匯出'];let currentStep=0;
function openDrawer(){document.querySelector('#tocDrawer')?.classList.add('open');document.querySelector('#drawerBackdrop').hidden=false;document.body.classList.add('drawer-open');}
function closeDrawer(){document.querySelector('#tocDrawer')?.classList.remove('open');document.querySelector('#drawerBackdrop').hidden=true;document.body.classList.remove('drawer-open');}
function setStep(i){currentStep=i;document.querySelectorAll('[data-tab]').forEach((x)=>{const isTarget=x.dataset.tab===steps[i];x.classList.toggle('active',isTarget);x.setAttribute('aria-current',isTarget?'step':'false');});document.querySelectorAll('.panel').forEach(x=>x.hidden=x.id!==steps[i]);document.querySelector('#backStep').disabled=i===0;document.querySelector('#nextStep').hidden=i===3;document.querySelector('#nextStep').textContent='下一步：'+stepNames[i+1];document.querySelector('#stepCount').textContent=`0${i+1} / 04`;const lbl=document.querySelector('#mobileStepLabel');if(lbl)lbl.textContent=`0${i+1} ${stepNames[i]}`;const badge=document.querySelector('#mobileStepBadge');if(badge)badge.textContent=`${i+1}/4`;document.querySelector('#'+steps[i]+' h2')?.focus({preventScroll:true});closeDrawer();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
document.querySelectorAll('[data-tab]').forEach((b)=>b.onclick=()=>{const idx=steps.indexOf(b.dataset.tab);if(idx!==-1)setStep(idx);});document.querySelector('#backStep').onclick=()=>setStep(Math.max(0,currentStep-1));document.querySelector('#nextStep').onclick=()=>setStep(Math.min(3,currentStep+1));document.querySelector('#toExport').onclick=()=>{setStep(3);document.querySelector('#style h2')?.scrollIntoView({behavior:'smooth'});};document.querySelector('#seePreview').onclick=()=>document.querySelector('#previewSection').scrollIntoView({behavior:'smooth'});
document.querySelector('#openDrawer')?.addEventListener('click',openDrawer);document.querySelector('#closeDrawer')?.addEventListener('click',closeDrawer);document.querySelector('#drawerBackdrop')?.addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer();});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{s.mode=b.dataset.mode;page=0;sync();});
document.querySelectorAll('[data-grid]').forEach(b=>b.onclick=()=>{s.grid=b.dataset.grid;page=0;sync();});
document.querySelectorAll('[data-colors]').forEach(b=>b.onclick=()=>{const p={blue:['#a6b6cc','#334155','#ffffff'],rose:['#c68d92','#653e46','#fffdfd'],green:['#80a49c','#2d5148','#ffffff'],gray:['#a1a1aa','#27272a','#ffffff']}[b.dataset.colors];colors.forEach(([k],i)=>s[k]=p[i]);sync();});
document.querySelector('#prev').onclick=()=>{page--;render();};document.querySelector('#next').onclick=()=>{page++;render();};document.querySelector('#zoomOut').onclick=()=>{autoFit=false;zoom=Math.max(15,zoom-10);applyZoom();};document.querySelector('#zoomIn').onclick=()=>{autoFit=false;zoom=Math.min(150,zoom+10);applyZoom();};document.querySelector('#fit').onclick=fit;
document.querySelector('#reset').onclick=()=>{if(confirm('還原全部文字與設定為預設值？')){s={...defaults};page=0;sync();toast('已還原預設設定');}};
let customCount=0;async function addFont(blob,label){const name='CustomFont'+(++customCount);const f=new FontFace(name,await blob.arrayBuffer());await f.load();document.fonts.add(f);const option=new Option(label,name);document.querySelector('[data-key="font"]').add(option);s.font=name;sync();toast('字型已套用');}
document.querySelector('#upload').onclick=()=>document.querySelector('#fontFile').click();document.querySelector('#fontFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024){toast('請選擇小於 20 MB 的字型');return;}try{await addFont(file,file.name.replace(/\.[^.]+$/,''));}catch{toast('無法讀取此字型，請確認檔案格式。');}e.target.value='';};
document.querySelector('#localFonts').onclick=async()=>{if(!window.queryLocalFonts){toast('此瀏覽器不支援本機字型讀取，請使用上傳字型。');return;}try{const fonts=await window.queryLocalFonts();const group=document.createElement('optgroup');group.label='本機字型';const existing=document.querySelector('optgroup');existing?.remove();for(const f of fonts){const o=new Option(f.fullName,'local:'+f.postscriptName);o._font=f;group.append(o);}document.querySelector('[data-key="font"]').append(group);toast(`已讀取 ${fonts.length} 款字型，請從字型選單選擇`);}catch{toast('未取得字型存取權限，你仍可上傳字型。');}};
document.querySelector('[data-key="font"]').addEventListener('change',async e=>{if(!e.target.value.startsWith('local:'))return;clearTimeout(debounce);try{await addFont(await e.target.selectedOptions[0]._font.blob(),e.target.selectedOptions[0].textContent);}catch{s.font=defaults.font;sync();toast('無法載入本機字型');}});
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
document.querySelector('#export').onclick=async()=>{if(busy)return;busy=true;document.querySelectorAll('.steps button').forEach(x=>x.disabled=true);document.querySelector('.editor').inert=true;document.querySelector('#reset').disabled=true;document.querySelector('#exportProgress').hidden=false;const b=document.querySelector('#export');b.disabled=true;try{await document.fonts.load(`20px "${s.font}"`,s.text||'永Aa');await document.fonts.load('14px "Noto Serif TC"',s.title+'日期');const l=layout(s);if(l.pages>80)throw new Error('字帖超過 80 頁，請減少內容或重複次數。');const pdf=new jsPDF({orientation:s.orientation,unit:'mm',format:[l.w,l.h],compress:true});pdf.setProperties({title:s.title||'さらさら字帖',creator:'さらさら'});const canvas=document.createElement('canvas');for(let i=0;i<l.pages;i++){b.innerHTML=`<span class="spinner"></span>匯出 ${i+1} / ${l.pages}`;document.querySelector('#exportProgress').value=(i+1)/l.pages*100;await new Promise(r=>setTimeout(r,10));draw(canvas,l,i,300/25.4);if(i)pdf.addPage([l.w,l.h],s.orientation);pdf.addImage(canvas.toDataURL('image/jpeg',0.95),'JPEG',0,0,l.w,l.h,undefined,'FAST');}download(pdf.output('blob'),(s.title||'さらさら字帖').replace(/[\\/:*?"<>|]/g,'_')+'.pdf');canvas.width=0;toast('PDF 已製作完成');}catch(err){toast(err.message||'匯出失敗，請重試');}finally{busy=false;document.querySelector('.editor').inert=false;document.querySelectorAll('.steps button').forEach(x=>x.disabled=false);document.querySelector('#reset').disabled=false;document.querySelector('#exportProgress').hidden=true;b.disabled=false;b.innerHTML=icon('download')+'<span>下載字帖 PDF</span>';}};
document.querySelector('#saveSettings').onclick=()=>download(new Blob([JSON.stringify({version:1,settings:{...s,font:fontList.some(([v])=>v===s.font)?s.font:defaults.font}},null,2)],{type:'application/json'}),'sarasara-settings.json');
document.querySelector('#loadSettings').onclick=()=>document.querySelector('#settingsFile').click();document.querySelector('#settingsFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100000)throw Error();const data=JSON.parse(await f.text());if(data.version!==1||!data.settings)throw Error();const next={...defaults};for(const[k,v]of Object.entries(migrateSettings(data.settings))){if(!(k in defaults)||typeof v!==typeof defaults[k])throw Error();const el=document.querySelector(`[data-key="${k}"]`);if(el?.type==='range'&&(!Number.isFinite(v)||v<Number(el.min)||v>Number(el.max)))throw Error();if(el?.tagName==='SELECT'&&![...el.options].some(o=>o.value===String(v)))throw Error();if(k.endsWith('Color')&&!/^#[a-f0-9]{6}$/i.test(v))throw Error();next[k]=v;}if(next.text.length>6000||next.title.length>40||!['mi','tian','square','nine','ruled','slant','lined','dots','none'].includes(next.grid))throw Error();s=next;page=0;sync();toast('設定已匯入');}catch{toast('設定檔格式不正確，請使用さらさら匯出的 JSON。');}e.target.value='';};
document.querySelector('#about').onclick=()=>document.querySelector('#help').showModal();document.querySelector('#closeHelp').onclick=()=>document.querySelector('#help').close();document.querySelector('#clearStorage').onclick=()=>{localStorage.removeItem('inkstone-settings');toast('本機紀錄已清除；再次編輯時會重新儲存。');};
const contentControls=bindContentControls({getState:()=>s,applyState:patch=>{Object.assign(s,patch);page=0;sync();},toast});
render().then(fit).catch(()=>toast('載入失敗，請重新整理'));window.addEventListener('resize',()=>{if(autoFit)fit();});
